Dataset/data_analysis/items
Paulina100/ML-for-TTRPG-game-design pull request #17
Opened 2023-08-01 20:07 UTC by tunczyk101

Mało (lub totalny brak) przydatnych danych

2023-08-01 20:33 UTC, tunczyk101 commented
Byłabym też wdzięczna jakbyście mogły mi potwierdzić, że ac["details"], allSaves/ saves: fortitude/will / traits - to raczej nie to co mam dodać -> trello
*"coś w stylu "Melee  hand +24 [+19/+14] (finesse, magical), Damage 4d8 negative plus paralyzing touch" (to akurat wzięte z Licha, więc jest dość specyficzne)"*

2023-08-02 19:19 UTC, Paulina100 approved these changes

2023-08-02 19:19 UTC, Paulina100 commented on notebooks/data_analysis/pathfinder_items_other_columns.ipynb
> +    "* name - *not important*\n",
ok

2023-08-02 19:19 UTC, Paulina100 commented on notebooks/data_analysis/pathfinder_items_other_columns.ipynb
> +    "* sort - **???**\n",
Też nie wiem co to do końca, ale no jest to jakiegoś rodzaju id czegoś tam więc można olać

2023-08-02 19:19 UTC, Paulina100 commented on notebooks/data_analysis/pathfinder_items_other_columns.ipynb
> +    "* type - **might be useful**\n",
Tak, to jest do tego: `"coś w stylu "Melee  hand +24 [+19/+14] (finesse, magical), Damage 4d8 negative plus paralyzing touch" (to akurat wzięte z Licha, więc jest dość specyficzne)"` 

i tego `"liczba czarów poszczególnych poziomów, np. Priest of Pharasma ma "Divine Prepared Spells DC 24, attack +16; 3rd [circle of protection](https://2e.aonprd.com/Spells.aspx?ID=38), [heal](https://2e.aonprd.com/Spells.aspx?ID=148) (x3), [searing light](https://2e.aonprd.com/Spells.aspx?ID=269) (x2); 2nd [gentle repose](https://2e.aonprd.com/Spells.aspx?ID=131), [silence](https://2e.aonprd.com/Spells.aspx?ID=287), [spiritual weapon](https://2e.aonprd.com/Spells.aspx?ID=306); 1st [disrupting weapons](https://2e.aonprd.com/Spells.aspx?ID=80), [mindlink](https://2e.aonprd.com/Spells.aspx?ID=195), [spirit link](https://2e.aonprd.com/Spells.aspx?ID=302); Cantrips (3rd) [detect magic](https://2e.aonprd.com/Spells.aspx?ID=66), [disrupt undead](https://2e.aonprd.com/Spells.aspx?ID=79), [light](https://2e.aonprd.com/Spells.aspx?ID=171), [read aura](https://2e.aonprd.com/Spells.aspx?ID=246), [shield](https://2e.aonprd.com/Spells.aspx?ID=280)" - czyli 6 czarów 3 poziomu, 3 czary 2 poziomu, 3 czary 1 poziomu (kantyczki raczej można odpuścić, one są słabe)"`

2023-08-02 19:19 UTC, Paulina100 commented on notebooks/data_analysis/pathfinder_items_other_columns.ipynb
> +    "    * pf2e:\n",
ok

2023-08-02 19:19 UTC, Paulina100 commented on notebooks/data_analysis/pathfinder_items_other_columns.ipynb
> +    "        * condition - *not important*\n"
ok

2023-08-02 19:19 UTC, Paulina100 commented on notebooks/data_analysis/pathfinder_items_other_columns.ipynb
> +    "        * linkedWeapon - maybe important if we are going to somehow count items of monster because e.g. Gancanagh have only one rapier (but a silver one)\n",
Myśle ze to jest niewazne, ten weapon powinien byc tez uwzgledniony jako atak po prostu
![image](https://github.com/Paulina100/ML-for-TTRPG-game-design/assets/92922548/c21827ea-b782-417b-9733-bdc68f50048b) 
Więc pewnie jest też wpisany jako action

2023-08-02 19:24 UTC, Paulina100 commented
> Byłabym też wdzięczna jakbyście mogły mi potwierdzić, że ac["details"], allSaves/ saves: fortitude/will / traits - to raczej nie to co mam dodać 

Chyba nie czaję pytania

2023-08-03 17:12 UTC, tunczyk101 commented
> > Byłabym też wdzięczna jakbyście mogły mi potwierdzić, że ac["details"], allSaves/ saves: fortitude/will / traits - to raczej nie to co mam dodać
> 
> Chyba nie czaję pytania

Chodziło mi o to, że te kolumny i pod-kolumny to nie te dane, których szukam (?)
// kolumny były analizowane wcześniej w notebookach dotyczących system

2023-08-05 20:33 UTC, bogumilap commented
Jeszcze mogłabyś dodać podumowanie do notebooks/readme, żeby wszystko w dalszym ciągu było zebrane w jednym miejscu

2023-08-05 20:34 UTC, bogumilap requested changes
Jeszcze mogłabyś dodać podsumowanie do notebooks/readme, żeby wszystko w dalszym ciągu było zebrane w jednym miejscu

2023-08-06 15:47 UTC, Paulina100 commented
> > > Byłabym też wdzięczna jakbyście mogły mi potwierdzić, że ac["details"], allSaves/ saves: fortitude/will / traits - to raczej nie to co mam dodać
> > 
> > 
> > Chyba nie czaję pytania
> 
> @Paulina100 Chodziło mi o to, że te kolumny i pod-kolumny to nie te dane, których szukam (?) // kolumny były analizowane wcześniej w notebookach dotyczących system

W takim razie, nie

2023-08-18 16:59 UTC, bogumilap approved these changes

2023-08-18 19:40 UTC, merged