Training/lightgbm
Paulina100/ML-for-TTRPG-game-design pull request #18
Opened 2023-08-08 18:46 UTC by Paulina100

2023-08-08 18:57 UTC, j-adamczyk approved these changes
To są naprawdę świetne wyniki!

2023-08-09 18:58 UTC, bogumilap requested changes
Czy nie chcemy mieć tego już w training/create_model (tak jak mamy tam pozostałe modele) i do tego zapisanego do pliku jako current_model? Obecny current_model chyba też mógłby zostać, tylko pod inną nazwą

2023-08-16 16:55 UTC, tunczyk101 commented
Wygląda ok.
Możesz jeszcze przy okazji dodać ten notebook ( oraz random forest ) do notebooks/readme

2023-08-16 16:56 UTC, tunczyk101 requested changes
Wygląda ok.
Możesz jeszcze przy okazji dodać ten notebook ( oraz random forest ) do notebooks/readme

2023-09-15 18:16 UTC, j-adamczyk approved these changes

2023-09-20 16:57 UTC, tunczyk101 approved these changes
Chyba już wszystko jest

2023-09-22 18:53 UTC, bogumilap approved these changes

2023-10-02 16:37 UTC, merged