Experiments
Paulina100/ML-for-TTRPG-game-design pull request #26
Opened 2023-10-31 12:38 UTC by Paulina100

2023-10-31 18:37 UTC, tunczyk101 approved these changes
Wygląda w miarę ok
Tylko te typy

2023-11-01 14:16 UTC, j-adamczyk requested changes
Parę uwag (w notebookach irytująco się komentuje):
1. Wykresy muszą mieć tytuły
2. Skrót od "number" to typowo "no" albo "#"
3. Tutaj to są bardziej "features" niż "characteristics", bo jednak niektóre są dość kreatywnie zdefiniowane, np. obrażenia
4. Co to znaczy "normal" w cechach? Jeżeli to jest brak tuningu, to oznaczyłbym jako "default" albo coś w tym stylu, bo "normal" kojarzy się od razu z normalizacją cech
5. Co robiło "minimise_overfitting"?
6. Jak zapisuejsz JSONy, to polecam opcję `indent=2`, wtedy ładnie to sformatuje
7. Zmieniłbym 8, 13, 50 na jakieś zestawy cech, które opiszecie w tekście. Typu np. "basic", "expanded", "full". Bo sama liczba cech to raczej artefakt obliczeń, a human-readable nazwy bardziej oddają to, co one robią

Ogólnie - bardzo fajna analiza, bardzo solidne wykresy.

2023-11-01 14:16 UTC, j-adamczyk commented on training/results.py
> +def print_check_predictions(y, y_pred):
+1

2023-11-01 14:16 UTC, j-adamczyk commented on training/results.py
> +    If 'threshold' is a float, values above the threshold are rounded up, and values below are rounded down.
Czemu po prostu nie zrobić domyślnej wartości 0.5?

2023-11-01 14:16 UTC, j-adamczyk commented on training/results.py
> +    mae_test = mean_absolute_error(y_test, y_pred_test)
Odpuściłbym MSE, tylko RMSE i MAE

2023-11-04 19:06 UTC, Paulina100 commented
> Parę uwag (w notebookach irytująco się komentuje):
> 
> 1. Wykresy muszą mieć tytuły
> 2. Skrót od "number" to typowo "no" albo "#"
> 3. Tutaj to są bardziej "features" niż "characteristics", bo jednak niektóre są dość kreatywnie zdefiniowane, np. obrażenia
> 4. Co to znaczy "normal" w cechach? Jeżeli to jest brak tuningu, to oznaczyłbym jako "default" albo coś w tym stylu, bo "normal" kojarzy się od razu z normalizacją cech
> 5. Co robiło "minimise_overfitting"?
> 6. Jak zapisuejsz JSONy, to polecam opcję `indent=2`, wtedy ładnie to sformatuje
> 7. Zmieniłbym 8, 13, 50 na jakieś zestawy cech, które opiszecie w tekście. Typu np. "basic", "expanded", "full". Bo sama liczba cech to raczej artefakt obliczeń, a human-readable nazwy bardziej oddają to, co one robią
> 
> Ogólnie - bardzo fajna analiza, bardzo solidne wykresy.

ad. 5. Zmniejsza głębokość drzewa (max_depth) żeby się nie przeuczało. Niewiele to dało, ale myślałam że tak się robi.

2023-11-09 15:52 UTC, j-adamczyk commented on notebooks/models/lightgbm/lightgbm_basic_results.json
> +{
W sumie czemu JSON, a nie CSV?

2023-11-09 15:54 UTC, j-adamczyk commented on training/results.py
> +def round_predictions(predict: np.ndarray, threshold: float = 0.5):
Zwracany typ to `np.ndarray`

2023-11-09 15:54 UTC, j-adamczyk commented on training/results.py
> +def print_check_predictions(y: pd.Series, y_pred: np.ndarray):
Zwraca `None`

2023-11-09 15:54 UTC, j-adamczyk commented on training/results.py
> +):
Zwraca `None`

2023-11-09 15:54 UTC, j-adamczyk commented on training/results.py
> +):
Plus może `evaluate_round_prediction`? Po funkcji z `check` w nazwie spodziewałbym się zwrotu boola

2023-11-09 15:55 UTC, j-adamczyk commented on training/results.py
> +):
Zwraca `None`

2023-11-09 15:55 UTC, j-adamczyk commented on training/results.py
> +):
Zwraca `None`

2023-11-10 11:47 UTC, merged