Display generated counterfactuals on frontend
Paulina100/ML-for-TTRPG-game-design pull request #30
Opened 2023-11-26 20:23 UTC by bogumilap

Wybieranie nowej wartości levelu, pobieranie wygenerowanych cf do plików JSON lub wstawienie wybranego cf do formularza
Śmiga też na awsie 💪

2023-11-27 11:34 UTC, j-adamczyk approved these changes

2023-11-27 11:34 UTC, j-adamczyk commented on docker/Dockerfile_aws
> +    ${FUNCTION_DIR}/pathfinder_2e_data/
Po co takie dane na serwerze?

2023-11-28 22:43 UTC, tunczyk101 requested changes
Nie znalazłam nigdzie CR
Trochę sobie poklikałam i pogrubienie/przyciemnienie się psuje 
Wzięłam potwora z pliku: jest ok
Wzięłam potwora z cfs: jest ok
Wpisywanie "ręcznie" lub submit nawet tych wartości wprost z pliku/cf (ale obliczanie levelu za pomocą submita z edytora): wszystko jest pogrubione.
Oprócz tego osobiście wolwłabym gdyby cf od razu po przeniesieniu ich do edytora (tak jak w przypadku zapisu), ale to już kwestia upodobań (?)

2023-11-29 20:13 UTC, tunczyk101 approved these changes
💜

2023-11-29 20:39 UTC, merged