Operate with full set of properties
Paulina100/ML-for-TTRPG-game-design pull request #35
Opened 2023-12-22 23:19 UTC by bogumilap

Przyzywam wszystkie siły do review 🙏
Przetestowałam na AWSie - działa

2023-12-23 09:07 UTC, j-adamczyk approved these changes

2023-12-27 11:27 UTC, tunczyk101 requested changes
Ogólnie jest ok.
Nie wiem, czy Ci się chce? / Czy to dużo poprawek (?), żeby dodać górne ograniczenie na focus (3).

Niestety pojawił mi się taki problem:
![image](https://github.com/Paulina100/ML-for-TTRPG-game-design/assets/92669642/984cf7a6-8a2f-4fdf-82b4-b8e3261ed1d9)
Modyfikacja cech w formsie: ataki. Najpierw ustawiłam bonusy na 0 a później chciałam zmienić avd_dmg. Tylko wyskakuje błąd, ale później działa normalnie: obliczenia itp.

oraz taki:
![image](https://github.com/Paulina100/ML-for-TTRPG-game-design/assets/92669642/09957e6b-e1bd-4f43-9279-ecac6c1eb002)
Pojawia się w momencie kiedy podają plik i z jakiegoś powodu nie przesyła się na front (nie wyświetla się nazwa: `monster.json`), ale ten błąd jest tak losowy, że nawet nie wiem jak go odtworzyć. Po prostu czasem jest.

2023-12-27 19:00 UTC, bogumilap commented on serving/frontend/src/utils.jsx
> +    let maxBonus = melee[0].bonus.value;
To jest lista obiektów i nie ma na to ładnego prostego zapisu, ale mogę zamienić na jednolinijkowy z użyciem funkcji reduce

2023-12-27 19:38 UTC, bogumilap commented
> oraz taki: ![image](https://private-user-images.githubusercontent.com/92669642/293019637-09957e6b-e1bd-4f43-9279-ecac6c1eb002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDM1OTYsIm5iZiI6MTcwMzcwMzI5NiwicGF0aCI6Ii85MjY2OTY0Mi8yOTMwMTk2MzctMDk5NTdlNmItZTFiZC00ZjQzLTkyNzktZWNhYzZjMWViMDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE4NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYzcxZjg4NWM4MTA4MDM5ZWJlMzlmYjVlMDg5MjczNmE1NTlmM2U3NDEzODAyMDU2NmU3ZmYyNjBjZWRkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YC8kYUOLRNmmCCuDfbozdVLlNrFrOi_necrGNko_7iU) Pojawia się w momencie kiedy podają plik i z jakiegoś powodu nie przesyła się na front (nie wyświetla się nazwa: `monster.json`), ale ten błąd jest tak losowy, że nawet nie wiem jak go odtworzyć. Po prostu czasem jest.

Niestety nie udało mi się odtworzyć tego błędu z plikiem... Dodałam łapanie błędu i wyświetlanie komunikatu, może będzie lepiej?

2023-12-28 18:40 UTC, tunczyk101 requested changes
Sprawdziłam.
Dzisiaj bez wyskakujących błędów. Dziękuję za poprawki tam, gdzie prosiłam. Tylko ten `focus`. (patrz niżej)

2023-12-28 18:40 UTC, tunczyk101 commented on serving/frontend/src/Components/Forms/FileForm.jsx
> +                        `smaller than or equal to ${maxPropertyValues.get(property)} ` +
Teraz dla `focus` podświetla się na czerwono, ale nadal można obliczyć poziom.

2023-12-28 18:40 UTC, tunczyk101 commented on serving/frontend/src/utils.jsx
> +    return Math.max(...bonusValues);
💜

2023-12-29 13:07 UTC, tunczyk101 approved these changes
Dzisiaj już nic nie udało mi się zepsuć. 😈 
Jest zacnie 💜

2023-12-29 14:09 UTC, Paulina100 commented on serving/frontend/src/Components/Forms/rules.jsx
> +    ["slashing_resistance", 0],
![image](https://github.com/Paulina100/ML-for-TTRPG-game-design/assets/92922548/0eb8b3a7-6856-4c05-bfcf-e8bf43ef030d)

Takie coś mi się wyświetla chodź nie wiem czemu

2023-12-29 14:14 UTC, Paulina100 approved these changes
W paru miejscach w tych pytajnikach się wyświetla undefined zamiast 0. Poza tym wszystko git

2023-12-29 14:14 UTC, Paulina100 commented on serving/frontend/src/Components/Forms/rules.jsx
> +    ["slashing_resistance", 0],
O chyba jak są nazwy zmiennych, które mają w sobie "-" to się wyświetla jako undefined

2023-12-29 19:00 UTC, merged